<?php
declare(strict_types=1);

namespace App\Services\AssetCreators;

use App\Services\PinterestBoardConfig;

final class PinterestIdeaPinCreator
{
    public function __construct(private PinterestPinRenderToolkit $toolkit) {}

    public function create(array $job, array $pair, int $pairOrder): array
    {
        $jobId = (int)$job['asset_creator_job_id'];
        $asset = $this->toolkit->sourceAsset($pair);
        $sourcePath = $this->toolkit->resolveImagePath($asset);
        $title = trim((string)($pair['search_title'] ?? $pair['pin_title'] ?? $pair['title'] ?? $job['title'] ?? 'ColorFix Ideas'));

        $canvas = $this->toolkit->canvas();
        $titleHeight = PinterestPinRenderToolkit::IDEA_TITLE_HEIGHT;
        $this->toolkit->drawIdeaTitle($canvas, $title);
        $this->toolkit->copyImageCover(
            $canvas,
            $sourcePath,
            0,
            $titleHeight,
            PinterestPinRenderToolkit::WIDTH,
            PinterestPinRenderToolkit::HEIGHT - $titleHeight
        );
        $this->toolkit->drawLogo($canvas);

        $relPath = $this->outputPath($jobId, $pairOrder, $pair, 'idea');
        $file = $this->toolkit->writeJpeg($canvas, $relPath);
        $metadata = $this->metadata($jobId, $pair, $pairOrder, $asset, 'idea', 'pin_idea');
        $libraryAsset = $this->toolkit->upsertPinAsset($relPath, [
            'asset_kind' => 'image',
            'mime_type' => 'image/jpeg',
            'title' => $title,
            'tags' => 'pin, pinterest, idea, generated',
            'alt_text' => trim((string)($metadata['description'] ?? '')),
            'note' => 'Generated by asset creator job #' . $jobId,
            'source_type' => 'asset_creator_job',
            'source_id' => $jobId,
            'client_id' => isset($asset['client_id']) && (int)$asset['client_id'] > 0 ? (int)$asset['client_id'] : null,
            'width' => PinterestPinRenderToolkit::WIDTH,
            'height' => PinterestPinRenderToolkit::HEIGHT,
            'file_size_bytes' => $file['file_size_bytes'],
            'checksum' => $file['checksum'],
            'metadata_json' => $metadata,
            'is_inactive' => 0,
            'is_retired' => 0,
        ]);

        return [
            'asset_library_id' => (int)$libraryAsset['asset_library_id'],
            'rel_path' => $relPath,
            'public_url' => $libraryAsset['public_url'] ?? $this->toolkit->publicUrl($relPath),
            'metadata' => $metadata,
        ];
    }

    protected function metadata(int $jobId, array $pair, int $pairOrder, array $asset, string $pinType, string $assetType): array
    {
        return [
            'creator_key' => 'pinterest.before_after_composite',
            'asset_creator_job_id' => $jobId,
            'pinterest_board' => PinterestBoardConfig::defaultBoard(),
            'pair_key' => $pair['pair_key'] ?? null,
            'pin_type' => $pinType,
            'asset_type' => $pair['asset_type'] ?? $assetType,
            'pair_order' => $pairOrder,
            'asset' => $asset,
            'after' => $asset,
            'search_title' => $pair['search_title'] ?? $pair['pin_title'] ?? $pair['title'] ?? '',
            'description' => $pair['description'] ?? $pair['pin_description'] ?? $pair['caption'] ?? '',
        ];
    }

    protected function outputPath(int $jobId, int $pairOrder, array $pair, string $slug): string
    {
        $pairKey = preg_replace('/[^a-z0-9_-]+/i', '-', (string)($pair['pair_key'] ?? "pair-{$pairOrder}"));
        $pairKey = trim((string)$pairKey, '-');
        if ($pairKey === '') {
            $pairKey = "pair-{$pairOrder}";
        }
        return "/photos/pins/generated/job-{$jobId}/pin-{$jobId}-{$pairOrder}-{$slug}-{$pairKey}.jpg";
    }
}
