CREATE TABLE IF NOT EXISTS supercats (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(80) NOT NULL,
  notes TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS supercat_clauses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supercat_id INT UNSIGNED NOT NULL,
  neutral_name VARCHAR(80) DEFAULT NULL,
  hue_name VARCHAR(80) DEFAULT NULL,
  light_name VARCHAR(80) DEFAULT NULL,
  chroma_name VARCHAR(80) DEFAULT NULL,
  notes VARCHAR(160) DEFAULT NULL,
  INDEX idx_supercat_clauses_super (supercat_id),
  FOREIGN KEY (supercat_id) REFERENCES supercats(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS color_supercats (
  color_id INT UNSIGNED NOT NULL,
  supercat_id INT UNSIGNED NOT NULL,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (color_id, supercat_id),
  INDEX idx_color_super_super (supercat_id),
  FOREIGN KEY (supercat_id) REFERENCES supercats(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
