CREATE TABLE IF NOT EXISTS master_roles (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(32) NOT NULL UNIQUE,
  display_name VARCHAR(64) NOT NULL,
  sort_order SMALLINT UNSIGNED DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS master_role_masks (
  mask_slug VARCHAR(64) PRIMARY KEY,
  role_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (role_id) REFERENCES master_roles(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
