CREATE TABLE `mask_blend_settings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `photo_id` bigint unsigned NOT NULL,
  `asset_id` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `mask_role` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `color_id` bigint unsigned DEFAULT NULL,
  `color_name` varchar(120) COLLATE utf8_unicode_ci DEFAULT NULL,
  `color_brand` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `color_code` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `color_hex` char(6) COLLATE utf8_unicode_ci NOT NULL,
  `base_lightness` decimal(5,2) NOT NULL,
  `target_lightness` decimal(5,2) NOT NULL,
  `target_h` decimal(6,2) DEFAULT NULL,
  `target_c` decimal(6,2) DEFAULT NULL,
  `blend_mode` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `blend_opacity` decimal(5,2) NOT NULL,
  `shadow_l_offset` float DEFAULT NULL,
  `shadow_tint_hex` char(7) COLLATE utf8_unicode_ci DEFAULT NULL,
  `shadow_tint_opacity` float DEFAULT NULL,
  `is_preset` tinyint(1) NOT NULL DEFAULT '0',
  `notes` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mask_blend_photo_role` (`photo_id`,`mask_role`),
  KEY `idx_mask_blend_asset_role` (`asset_id`,`mask_role`),
  KEY `idx_mask_blend_lightness` (`base_lightness`,`target_lightness`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
